export const skillsData = {
    "Backend & APIs": ["Node.js", "Java", "Spring Boot", "gRPC", "REST", "SOAP"],
    Frontend: [
        "JavaScript (ES6+)",
        "React.js",
        "Next.js",
        "Node.js",
        "HTML/CSS",
        "Redux",
        "jest",
    ],
    "Databases & Caching": ["PostgreSQL", "MongoDB", "Nginx"],
    "Systems Programming": ["C++", "C-Harbour", "xHarbour", "Rust"],
    "DevOps & Tools": [
        "Docker",
        "AWS",
        "Linux",
        "HTTP/HTTPS",
        "FTP",
        "Git",
        "CI/CD principles",
    ],
    Methodologies: ["Agile/Scrum", "Parallel Processing", "Code Refactoring"],
    "Soft Skills": [
        "Communication",
        "Teamwork",
        "Problem Solving",
        "Leadership",
        "Adaptability",
        "Critical Thinking",
        "Time Management",
        "Active Listening",
        "Empathy",
        "Creativity",
    ],
};
